require("camellia.core")
require("camellia.lazy")
--

-- require('neovim-lua.core/lazy')
-- require('neovim-lua.core/autocmds')
-- require('neovim-lua.core/keymaps')
-- require('neovim-lua.core/colors')
-- require('neovim-lua.core/statusline')
-- require('neovim-lua.core/options')
-- require('neovim-lua.lsp/lspconfig')
-- require('neovim-lua.plugins/nvim-tree')
-- require('neovim-lua.plugins/indent-blankline')
-- require('neovim-lua.plugins/nvim-cmp')
-- require('neovim-lua.plugins/nvim-treesitter')
-- require('neovim-lua.plugins/alpha-nvim')
